packages:
  - packages/*

catalogs:
  deps:
    '@turf/turf': ^7.2.0
    '@unocss/reset': ^66.1.4
    '@vueuse/core': ^13.3.0
    '@vueuse/shared': ^13.3.0
    cesium: ^1.130.0
    pinia: ^3.0.3
    vue: ^3.5.16
    vue-router: ^4.5.1
